<a href="https://colab.research.google.com/github/vikasprph/clinical-pharmacy-analytics/blob/main/Clinical_Insight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

"""
Clinical Pharmacy Analytics Project

Objective:
Analyze pharmacy claims data to identify cost drivers and recommend
clinical interventions to reduce spend and improve utilization.

Tools Used:
- Python (pandas)
- SQL (for aggregation and insights)
- Tableau (for visualization)
"""

# =========================
# Clinical Recommendations Logic
# =========================

In [2]:
# =========================
# Load Pharmacy Claims Data
# =========================

import pandas as pd

df = pd.read_csv("pharmacy_claims_final.csv")
df.head()

,patient_id,age,gender,diagnosis,drug_name,brand_or_generic,days_supply,claim_cost,site_of_care,savings_opportunity,estimated_savings
0,1,58,M,Rheumatoid Arthritis,Lantus,Brand,30,685,Retail,Lower-cost insulin review,137.0
1,2,48,M,Rheumatoid Arthritis,Lantus,Brand,90,371,Retail,Lower-cost insulin review,74.2
2,3,32,F,Atrial Fibrillation,Xarelto,Brand,60,1063,Specialty,No immediate opportunity,0.0
3,4,50,M,Hyperlipidemia,Ozempic,Brand,60,785,Specialty,No immediate opportunity,0.0
4,5,56,M,Hypertension,Diovan,Brand,90,198,Specialty,Generic ARB opportunity,128.7

# =========================
# Clinical Opportunity Analysis
# =========================

In [ ]:
def recommendation(row):
    if row["drug_name"] == "Crestor":
        return "Switch to generic statin"
    elif row["drug_name"] == "Diovan":
        return "Switch to valsartan"
    elif row["drug_name"] == "Humira":
        return "Evaluate biosimilar"
    elif row["drug_name"] == "Stelara":
        return "Specialty drug review"
    elif row["drug_name"] == "Lantus":
        return "Consider lower-cost insulin"
    elif row["drug_name"] == "Ozempic":
        return "Assess formulary alternatives"
    else:
        return "No change"

df["recommendation"] = df.apply(recommendation, axis=1)

In [ ]:
def priority(row):
    if row["estimated_savings"] > 1000:
        return "High Priority"
    elif row["estimated_savings"] > 200:
        return "Medium Priority"
    else:
        return "Low Priority"

df["priority_level"] = df.apply(priority, axis=1)

In [ ]:
df.groupby("recommendation")["estimated_savings"].sum().sort_values(ascending=False)

recommendation
Evaluate biosimilar              24145.80
Specialty drug review             8053.60
Switch to generic statin          4132.80
Switch to valsartan               2803.45
Consider lower-cost insulin       1951.80
Assess formulary alternatives        0.00
No change                            0.00
Name: estimated_savings, dtype: float64

In [ ]:
def generate_report(df):
    total_spend = df["claim_cost"].sum()
    total_savings = df["estimated_savings"].sum()

    print("===== Pharmacy Analytics Report =====")
    print(f"Total Spend: ${total_spend:,.0f}")
    print(f"Estimated Savings: ${total_savings:,.0f}")

    print("\nTop Cost Drivers:")
    print(df.groupby("drug_name")["claim_cost"].sum().sort_values(ascending=False).head(5))

    print("\nTop Savings Opportunities:")
    print(df.groupby("recommendation")["estimated_savings"].sum().sort_values(ascending=False).head(5))

generate_report(df)

===== Pharmacy Analytics Report =====
Total Spend: $279,482
Estimated Savings: $41,087

Top Cost Drivers:
drug_name
Humira     120729
Stelara     80536
Eliquis     18384
Xarelto     16439
Ozempic     14210
Name: claim_cost, dtype: int64

Top Savings Opportunities:
recommendation
Evaluate biosimilar            24145.80
Specialty drug review           8053.60
Switch to generic statin        4132.80
Switch to valsartan             2803.45
Consider lower-cost insulin     1951.80
Name: estimated_savings, dtype: float64

# =========================
# Priority Classification
# =========================

In [ ]:
df.groupby("priority_level")["estimated_savings"].sum()

priority_level
High Priority       9877.60
Low Priority        6067.90
Medium Priority    25141.95
Name: estimated_savings, dtype: float64

# =========================
# Automated Report Generation
# =========================

In [5]:
df.to_csv("clinical_pharmacy_analytics_output.csv", index=False)

In [ ]:
from google.colab import files
files.download("pharmacy_claims_v2.csv")

In [3]:
df.head(10)

,patient_id,age,gender,diagnosis,drug_name,brand_or_generic,days_supply,claim_cost,site_of_care,savings_opportunity,estimated_savings
0,1,58,M,Rheumatoid Arthritis,Lantus,Brand,30,685,Retail,Lower-cost insulin review,137.0
1,2,48,M,Rheumatoid Arthritis,Lantus,Brand,90,371,Retail,Lower-cost insulin review,74.2
2,3,32,F,Atrial Fibrillation,Xarelto,Brand,60,1063,Specialty,No immediate opportunity,0.0
3,4,50,M,Hyperlipidemia,Ozempic,Brand,60,785,Specialty,No immediate opportunity,0.0
4,5,56,M,Hypertension,Diovan,Brand,90,198,Specialty,Generic ARB opportunity,128.7
5,6,81,F,Diabetes,Eliquis,Brand,90,966,Retail,No immediate opportunity,0.0
6,7,50,M,Hypertension,Eliquis,Brand,30,1046,Specialty,No immediate opportunity,0.0
7,8,38,F,Atrial Fibrillation,Stelara,Brand,60,5041,Mail Order,Specialty drug utilization review,504.1
8,9,37,M,Rheumatoid Arthritis,Lantus,Brand,60,677,Retail,Lower-cost insulin review,135.4
9,10,69,F,Hypertension,Xarelto,Brand,60,961,Specialty,No immediate opportunity,0.0

In [4]:
print("\nClinical Insight:")
print("High-cost specialty drugs (Humira, Stelara) are the primary cost drivers.")
print("Biosimilar and specialty review interventions represent the largest savings opportunity.")

Clinical Insight:
High-cost specialty drugs (Humira, Stelara) are the primary cost drivers.
Biosimilar and specialty review interventions represent the largest savings opportunity.