<a href="https://colab.research.google.com/github/vikasprph/clinical-pharmacy-analytics/blob/main/Drug_Analysis_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("pharmacy_claims_final.csv")
df.head()

,patient_id,age,gender,diagnosis,drug_name,brand_or_generic,days_supply,claim_cost,site_of_care,savings_opportunity,estimated_savings
0,1,58,M,Rheumatoid Arthritis,Lantus,Brand,30,685,Retail,Lower-cost insulin review,137.0
1,2,48,M,Rheumatoid Arthritis,Lantus,Brand,90,371,Retail,Lower-cost insulin review,74.2
2,3,32,F,Atrial Fibrillation,Xarelto,Brand,60,1063,Specialty,No immediate opportunity,0.0
3,4,50,M,Hyperlipidemia,Ozempic,Brand,60,785,Specialty,No immediate opportunity,0.0
4,5,56,M,Hypertension,Diovan,Brand,90,198,Specialty,Generic ARB opportunity,128.7

In [ ]:
def recommendation(row):
    if row["drug_name"] == "Crestor":
        return "Switch to generic statin"
    elif row["drug_name"] == "Diovan":
        return "Switch to generic valsartan"
    elif row["drug_name"] == "Humira":
        return "Evaluate biosimilar option"
    elif row["drug_name"] == "Stelara":
        return "Specialty utilization review"
    elif row["drug_name"] == "Lantus":
        return "Evaluate lower-cost insulin alternative"
    elif row["drug_name"] == "Ozempic":
        return "Assess formulary alternatives"
    elif row["drug_name"] in ["Eliquis", "Xarelto"]:
        return "Review anticoagulant utilization"
    else:
        return "No immediate recommendation"

df["recommendation"] = df.apply(recommendation, axis=1)

df[["drug_name", "claim_cost", "estimated_savings", "recommendation"]].head(20)

,drug_name,claim_cost,estimated_savings,recommendation
0,Lantus,685,137.0,Evaluate lower-cost insulin alternative
1,Lantus,371,74.2,Evaluate lower-cost insulin alternative
2,Xarelto,1063,0.0,Review anticoagulant utilization
3,Ozempic,785,0.0,Assess formulary alternatives
4,Diovan,198,128.7,Switch to generic valsartan
5,Eliquis,966,0.0,Review anticoagulant utilization
6,Eliquis,1046,0.0,Review anticoagulant utilization
7,Stelara,5041,504.1,Specialty utilization review
8,Lantus,677,135.4,Evaluate lower-cost insulin alternative
9,Xarelto,961,0.0,Review anticoagulant utilization
10,Ozempic,505,0.0,Assess formulary alternatives
11,Metformin,48,0.0,No immediate recommendation
12,Crestor,339,237.3,Switch to generic statin
13,Jardiance,529,0.0,No immediate recommendation
14,Humira,6928,1385.6,Evaluate biosimilar option
15,Eliquis,992,0.0,Review anticoagulant utilization
16,Jardiance,480,0.0,No immediate recommendation
17,Lantus,656,131.2,Evaluate lower-cost insulin alternative
18,Eliquis,1138,0.0,Review anticoagulant utilization
19,Metformin,18,0.0,No immediate recommendation

In [ ]:
recommendation_summary = (
    df.groupby("recommendation")["estimated_savings"]
    .sum()
    .sort_values(ascending=False)
)

recommendation_summary

recommendation
Evaluate biosimilar option                 24145.80
Specialty utilization review                8053.60
Switch to generic statin                    4132.80
Switch to generic valsartan                 2803.45
Evaluate lower-cost insulin alternative     1951.80
Assess formulary alternatives                  0.00
No immediate recommendation                    0.00
Review anticoagulant utilization               0.00
Name: estimated_savings, dtype: float64

In [ ]:
df.to_csv("pharmacy_claims_with_recommendations.csv", index=False)

In [ ]:
files.download("pharmacy_claims_with_recommendations.csv")

In [ ]:
import pandas as pd

df = pd.read_csv("pharmacy_claims_with_recommendations.csv")

In [ ]:
def priority_level(row):
    if row["estimated_savings"] > 1000:
        return "High Priority"
    elif row["estimated_savings"] > 200:
        return "Medium Priority"
    else:
        return "Low Priority"

df["priority_level"] = df.apply(priority_level, axis=1)

In [ ]:
df[["drug_name", "estimated_savings", "priority_level"]].head(20)

    drug_name  estimated_savings   priority_level
0      Lantus              137.0     Low Priority
1      Lantus               74.2     Low Priority
2     Xarelto                0.0     Low Priority
3     Ozempic                0.0     Low Priority
4      Diovan              128.7     Low Priority
5     Eliquis                0.0     Low Priority
6     Eliquis                0.0     Low Priority
7     Stelara              504.1  Medium Priority
8      Lantus              135.4     Low Priority
9     Xarelto                0.0     Low Priority
10    Ozempic                0.0     Low Priority
11  Metformin                0.0     Low Priority
12    Crestor              237.3  Medium Priority
13  Jardiance                0.0     Low Priority
14     Humira             1385.6    High Priority
15    Eliquis                0.0     Low Priority
16  Jardiance                0.0     Low Priority
17     Lantus              131.2     Low Priority
18    Eliquis                0.0     Low Priority
19  Metformin                0.0     Low Priority

In [ ]:
df.groupby("priority_level")["estimated_savings"].sum()

priority_level
High Priority       9877.60
Low Priority        6067.90
Medium Priority    25141.95
Name: estimated_savings, dtype: float64

In [ ]:
df.to_csv("pharmacy_claims_final_v2.csv", index=False)

In [ ]:
from google.colab import files
files.download("pharmacy_claims_final_v2.csv")